CREATE SEQUENCE PLACES_SEQUENCE
    START 1
    INCREMENT 1
    ;

CREATE TABLE PLACES (
    id BIGINT DEFAULT nextval('PLACES_SEQUENCE') NOT NULL,
    address VARCHAR(100) NOT NULL,
    info VARCHAR(200) NOT NULL,
    name VARCHAR(90) NOT NULL,
    primary key (id)
);

ALTER TABLE
IF EXISTS PLACES
ADD CONSTRAINT PLACE_NAME_AND_ADDRESS_CONSTRAINT UNIQUE (name, address);